// nest-next/next/src/app/users/page.tsx
'use client';

import { useQuery } from '@apollo/client';
import { GET_USERS } from '@/lib/graphql/queries';
import Link from 'next/link';

interface User {
  id: string;
  email: string;
  username: string;
  createdAt: string;
  posts: Array<{
    id: string;
    title: string;
    published: boolean;
  }>;
}

export default function UsersPage() {
  const { data, loading, error } = useQuery<{ users: User[] }>(GET_USERS);

  if (loading) {
    return (
      <div className="min-h-screen p-8 flex items-center justify-center">
        <div className="text-xl">読み込み中...</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen p-8 flex items-center justify-center">
        <div className="text-xl text-red-600">
          エラー: {error.message}
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen p-8">
      <div className="max-w-6xl mx-auto">
        <div className="flex justify-between items-center mb-8">
          <h1 className="text-3xl font-bold">ユーザー一覧</h1>
          <Link
            href="/"
            className="px-4 py-2 bg-gray-500 text-white rounded hover:bg-gray-600"
          >
            ホームに戻る
          </Link>
        </div>

        {data?.users && data.users.length === 0 ? (
          <p className="text-gray-600">ユーザーが登録されていません。</p>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {data?.users.map((user) => (
              <div
                key={user.id}
                className="p-6 border rounded-lg bg-white shadow-sm hover:shadow-md transition"
              >
                <h2 className="text-xl font-bold mb-2">{user.username}</h2>
                <p className="text-sm text-gray-600 mb-2">{user.email}</p>
                <p className="text-xs text-gray-500 mb-4">
                  登録日: {new Date(user.createdAt).toLocaleDateString('ja-JP')}
                </p>
                
                {user.posts && user.posts.length > 0 && (
                  <div className="mt-4">
                    <p className="text-sm font-semibold mb-2">
                      投稿 ({user.posts.length})
                    </p>
                    <ul className="text-sm text-gray-600 space-y-1">
                      {user.posts.slice(0, 3).map((post) => (
                        <li key={post.id} className="truncate">
                          • {post.title}
                          {post.published && (
                            <span className="ml-2 text-green-600">公開中</span>
                          )}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

// sveltekit/src/routes/users/+page.svelte
<script lang="ts">
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();
</script>

<div class="users">
	<h1>👥 ユーザー一覧</h1>
	<p class="description">
		Prisma ORMを使用してPostgreSQLからデータを取得しています (SSR)
	</p>

	{#if data.users.length === 0}
		<div class="empty">
			<p>ユーザーが登録されていません。</p>
			<p class="hint">データベースにサンプルデータを追加してください。</p>
		</div>
	{:else}
		<div class="grid">
			{#each data.users as user (user.id)}
				<div class="user-card">
					<div class="user-header">
						<div class="avatar">
							{user.username.charAt(0).toUpperCase()}
						</div>
						<div class="user-info">
							<h3>{user.username}</h3>
							<p class="email">{user.email}</p>
						</div>
					</div>
					<div class="user-meta">
						<p class="date">
							登録日: {new Date(user.createdAt).toLocaleDateString('ja-JP')}
						</p>
						{#if user.posts.length > 0}
							<p class="posts-count">
								投稿: {user.posts.length}件
							</p>
						{/if}
					</div>
				</div>
			{/each}
		</div>
	{/if}
</div>

<style>
	.users {
		max-width: 1000px;
		margin: 0 auto;
	}

	h1 {
		font-size: 2.5rem;
		margin-bottom: 0.5rem;
		color: #333;
	}

	.description {
		color: #666;
		margin-bottom: 2rem;
		font-size: 1.1rem;
	}

	.empty {
		text-align: center;
		padding: 3rem;
		background: #f9f9f9;
		border-radius: 8px;
	}

	.empty p {
		font-size: 1.1rem;
		color: #666;
		margin-bottom: 0.5rem;
	}

	.hint {
		font-size: 0.9rem;
		color: #999;
	}

	.grid {
		display: grid;
		grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
		gap: 1.5rem;
	}

	.user-card {
		background: white;
		padding: 1.5rem;
		border-radius: 12px;
		box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
		transition: transform 0.2s, box-shadow 0.2s;
	}

	.user-card:hover {
		transform: translateY(-4px);
		box-shadow: 0 4px 16px rgba(0, 0, 0, 0.15);
	}

	.user-header {
		display: flex;
		align-items: center;
		gap: 1rem;
		margin-bottom: 1rem;
	}

	.avatar {
		width: 60px;
		height: 60px;
		border-radius: 50%;
		background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
		display: flex;
		align-items: center;
		justify-content: center;
		color: white;
		font-size: 1.5rem;
		font-weight: bold;
	}

	.user-info h3 {
		margin: 0 0 0.25rem 0;
		font-size: 1.3rem;
		color: #333;
	}

	.email {
		margin: 0;
		color: #666;
		font-size: 0.9rem;
	}

	.user-meta {
		padding-top: 1rem;
		border-top: 1px solid #eee;
	}

	.user-meta p {
		margin: 0.25rem 0;
		font-size: 0.9rem;
		color: #999;
	}

	.posts-count {
		color: #4075a6 !important;
		font-weight: 500;
	}
</style>
