// nest-next/next/src/app/graphql/page.tsx
'use client';

import Link from 'next/link';

export default function GraphQLPage() {
  const apiUrl = process.env.NEXT_PUBLIC_GRAPHQL_ENDPOINT || 'http://localhost:4000/graphql';

  return (
    <div className="min-h-screen p-8">
      <div className="max-w-4xl mx-auto">
        <div className="flex justify-between items-center mb-8">
          <h1 className="text-3xl font-bold">GraphQL API</h1>
          <Link
            href="/"
            className="px-4 py-2 bg-gray-500 text-white rounded hover:bg-gray-600"
          >
            ホームに戻る
          </Link>
        </div>

        <div className="space-y-6">
          <div className="p-6 border rounded-lg bg-white shadow-sm">
            <h2 className="text-xl font-bold mb-4">🔗 GraphQL エンドポイント</h2>
            <p className="text-gray-700 mb-2">
              バックエンドのGraphQL APIは以下のエンドポイントで利用可能です:
            </p>
            <code className="block p-4 bg-gray-100 rounded text-sm">
              {apiUrl}
            </code>
            <a
              href={apiUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-block mt-4 px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600"
            >
              GraphQL Playground を開く
            </a>
          </div>

          <div className="p-6 border rounded-lg bg-white shadow-sm">
            <h2 className="text-xl font-bold mb-4">📝 クエリ例</h2>
            
            <h3 className="font-semibold mt-4 mb-2">すべてのユーザーを取得:</h3>
            <pre className="p-4 bg-gray-100 rounded text-sm overflow-x-auto">
{`query {
  users {
    id
    email
    username
    createdAt
    posts {
      id
      title
      published
    }
  }
}`}
            </pre>

            <h3 className="font-semibold mt-4 mb-2">ユーザーを作成:</h3>
            <pre className="p-4 bg-gray-100 rounded text-sm overflow-x-auto">
{`mutation {
  createUser(
    email: "test@example.com"
    username: "testuser"
    password: "password123"
  ) {
    id
    email
    username
    createdAt
  }
}`}
            </pre>

            <h3 className="font-semibold mt-4 mb-2">すべての投稿を取得:</h3>
            <pre className="p-4 bg-gray-100 rounded text-sm overflow-x-auto">
{`query {
  posts {
    id
    title
    content
    published
    createdAt
    author {
      id
      username
    }
  }
}`}
            </pre>
          </div>

          <div className="p-6 border rounded-lg bg-white shadow-sm">
            <h2 className="text-xl font-bold mb-4">🛠️ Apollo Client の使用例</h2>
            <p className="text-gray-700 mb-2">
              このプロジェクトでは Apollo Client を使用してGraphQLクエリを実行しています。
            </p>
            <pre className="p-4 bg-gray-100 rounded text-sm overflow-x-auto">
{`import { useQuery } from '@apollo/client';
import { GET_USERS } from '@/lib/graphql/queries';

function MyComponent() {
  const { data, loading, error } = useQuery(GET_USERS);
  
  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error: {error.message}</p>;
  
  return (
    <div>
      {data.users.map(user => (
        <div key={user.id}>{user.username}</div>
      ))}
    </div>
  );
}`}
            </pre>
          </div>
        </div>
      </div>
    </div>
  );
}

// nuxt/pages/graphql.vue
<template>
  <div class="max-w-4xl mx-auto">
    <h1 class="text-4xl font-bold text-gray-900 mb-8">GraphQL (CSR) - urql</h1>

    <div class="bg-white p-8 rounded-lg shadow-md mb-8">
      <h2 class="text-2xl font-semibold text-gray-900 mb-4">🔄 クライアントサイドレンダリング</h2>
      <p class="text-gray-600 mb-4">
        urqlを使用したGraphQLクエリの例です。クライアントサイドでデータを取得します。
      </p>

      <!-- データ取得状態の表示 -->
      <div v-if="fetching" class="text-center py-8">
        <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-green-600 mx-auto"></div>
        <p class="text-gray-600 mt-4">Loading...</p>
      </div>

      <div v-else-if="error" class="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded">
        <p class="font-semibold">エラーが発生しました:</p>
        <p>{{ error.message }}</p>
      </div>

      <div v-else class="space-y-4">
        <div class="bg-green-50 border border-green-200 text-green-700 px-4 py-3 rounded">
          <p>GraphQLエンドポイント: {{ config.public.graphqlEndpoint }}</p>
          <p class="text-sm mt-2">※ サンプルクエリです。実際のGraphQL APIに接続してください。</p>
        </div>
      </div>
    </div>

    <div class="bg-blue-50 p-6 rounded-lg">
      <h3 class="font-semibold mb-2">urql使用例:</h3>
      <pre class="bg-gray-800 text-white p-4 rounded overflow-x-auto text-sm"><code>// composables/useGraphQL.ts
import { useQuery } from '@urql/vue'

export const useUsers = () => {
  const query = `
    query {
      users {
        id
        username
        email
      }
    }
  `
  
  return useQuery({ query })
}</code></pre>
    </div>

    <div class="mt-8 text-center">
      <NuxtLink to="/" class="text-green-600 hover:underline">← ホームに戻る</NuxtLink>
    </div>
  </div>
</template>

<script setup lang="ts">
const config = useRuntimeConfig()

// サンプルクエリ（実際のエンドポイントに接続する場合はコメントを外す）
const SAMPLE_QUERY = `
  query {
    # ここにGraphQLクエリを記述
    # 例: users { id username email }
  }
`

// urql使用例（実際に使用する場合）
// const { data, fetching, error } = await useQuery({ query: SAMPLE_QUERY })

// デモ用のダミーデータ
const fetching = ref(false)
const error = ref(null)
const data = ref(null)

useHead({
  title: 'GraphQL - Nuxt テンプレート',
  meta: [
    { name: 'description', content: 'urqlを使用したGraphQLクエリの例' }
  ]
})
</script>
